version: "3.3"

services:
  nginx:
    build: ./nginx
    ports:
      - "8899:80"
    volumes:
      - ./nginx/logs:/var/logs/nginx/:rw
    networks:
      - frontend

  swoole:
    build: ./swoole
    ports:
      - "9501"
    networks:
      - frontend
      - backend

  cgi:
    build: ./cgi
    ports:
      - "9000"
    # tty: true
    networks:
      - frontend
      - backend

  nodejs:
    build: ./nodejs
    ports:
      - "3000"
    networks:
      - frontend
      - backend

  mysql:
    image: "mysql:5.7"
    ports:
      - 3306
    volumes:
      - ./mysql:/data/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - backend

  redis:
    image: "redis"
    ports:
      - 6379
    networks:
      - backend

networks:
  frontend:
  backend:
